
### INICIAR SESION
POST http://localhost:4000/auth/iniciar_sesion
Content-Type: application/json

{
    "user_name": "MARGARITA",
    "password": "123456"
}

### REGISTRAR USUARIO
POST http://localhost:4000/auth/registrar_usuario
Content-Type: application/json

{
    "user_name": "MARGARITA2",
    "password": "123456"
}

### Renovar token
GET http://localhost:4000/auth/validar_usuario
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTM4OGEyOWY3OGQzMTU0ZWVlZmI5MCIsImlhdCI6MTcwOTQxMDQ2NiwiZXhwIjoxNzA5NDI0ODY2fQ.nwis0BnJKAKAEacUwSh54aaA_RuJu338a2xFeMeiPnM